### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy

### ISSUE THREAD

**Issue by ChockChan** [klarna/HiveRunner#66]
When i am using hiverunner(3.0.0) and running the test, I meet some exception like this:

```
java.lang.NoSuchMethodError: org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(Lorg/apache/hadoop/hive/conf/HiveConf;Lorg/apache/hadoop/hive/metastore/HiveMetaHookLoader;Ljava/util/Map;Ljava/lang/String;)Lorg/apache/hadoop/hive/metastore/IMetaStoreClient;
	at org.apache.hadoop.hive.ql.metadata.Hive.createMetaStoreClient(Hive.java:3005)
	at org.apache.hadoop.hive.ql.metadata.Hive.getMSC(Hive.java:3024)
	at org.apache.hadoop.hive.ql.metadata.Hive.getAllDatabases(Hive.java:1234)
	at org.apache.hadoop.hive.ql.metadata.Hive.reloadFunctions(Hive.java:174)
	at org.apache.hadoop.hive.ql.metadata.Hive.<clinit>(Hive.java:166)
	at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:503)
	at org.apache.hive.service.cli.CLIService.applyAuthorizationConfigPolicy(CLIService.java:125)
	at org.apache.hive.service.cli.CLIService.init(CLIService.java:110)
	at org.apache.hive.service.CompositeService.init(CompositeService.java:59)
	at org.apache.hive.service.server.HiveServer2.init(HiveServer2.java:129)
	at com.klarna.hiverunner.HiveServerContainer.init(HiveServerContainer.java:85)
	at com.klarna.hiverunner.builder.HiveShellBase.start(HiveShellBase.java:150)
	at com.klarna.hiverunner.StandaloneHiveRunner.createHiveServerContainer(StandaloneHiveRunner.java:224)
	at com.klarna.hiverunner.StandaloneHiveRunner.evaluateStatement(StandaloneHiveRunner.java:176)
	at com.klarna.hiverunner.StandaloneHiveRunner.access$000(StandaloneHiveRunner.java:65)
	at com.klarna.hiverunner.StandaloneHiveRunner$1$1.evaluate(StandaloneHiveRunner.java:92)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at com.klarna.hiverunner.ThrowOnTimeout$1.run(ThrowOnTimeout.java:42)
	at java.lang.Thread.run(Thread.java:745)
```

Can anybody help resolve this exception? Thanks

**Comment by PelleUllberg** [comment]
Looks like you either are
1. Missing org.apache.hadoop.hive.metastore.RetryingMetaStoreClient on the
classpath
2. Have the wrong version of
org.apache.hadoop.hive.metastore.RetryingMetaStoreClient
on the classpath
3. Have multiple versions of
org.apache.hadoop.hive.metastore.RetryingMetaStoreClient
on the classpath

run 'mvn dependency:tree' and see how many versions you have of artifact
'hive-metastore'. regards
/Pelle

**Comment by ChockChan** [comment]
Thanks for @PelleUllberg ! I have multiple version of hive.metastore on the classpath.
However, I have met another exceptions.

```
java.lang.IllegalStateException: Failed to create HiveServer :Error applying authorization policy on hive configuration: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient
	at com.klarna.hiverunner.HiveServerContainer.init(HiveServerContainer.java:102)
	at com.klarna.hiverunner.builder.HiveShellBase.start(HiveShellBase.java:150)
	at com.klarna.hiverunner.StandaloneHiveRunner.createHiveServerContainer(StandaloneHiveRunner.java:224)
	at com.klarna.hiverunner.StandaloneHiveRunner.evaluateStatement(StandaloneHiveRunner.java:176)
	at com.klarna.hiverunner.StandaloneHiveRunner.access$000(StandaloneHiveRunner.java:65)
	at com.klarna.hiverunner.StandaloneHiveRunner$1$1.evaluate(StandaloneHiveRunner.java:92)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at com.klarna.hiverunner.ThrowOnTimeout$1.run(ThrowOnTimeout.java:42)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Error applying authorization policy on hive configuration: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient
	at org.apache.hive.service.cli.CLIService.init(CLIService.java:112)
	at org.apache.hive.service.CompositeService.init(CompositeService.java:59)
	at org.apache.hive.service.server.HiveServer2.init(HiveServer2.java:129)
	at com.klarna.hiverunner.HiveServerContainer.init(HiveServerContainer.java:85)
	at com.klarna.hiverunner.builder.HiveShellBase.start(HiveShellBase.java:150)
	at com.klarna.hiverunner.StandaloneHiveRunner.createHiveServerContainer(StandaloneHiveRunner.java:224)
	at com.klarna.hiverunner.StandaloneHiveRunner.evaluateStatement(StandaloneHiveRunner.java:176)
	at com.klarna.hiverunner.StandaloneHiveRunner.access$000(StandaloneHiveRunner.java:65)
	at com.klarna.hiverunner.StandaloneHiveRunner$1$1.evaluate(StandaloneHiveRunner.java:92)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at com.klarna.hiverunner.ThrowOnTimeout$1.run(ThrowOnTimeout.java:42)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient
	at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:522)
	at org.apache.hive.service.cli.CLIService.applyAuthorizationConfigPolicy(CLIService.java:125)
	at org.apache.hive.service.cli.CLIService.init(CLIService.java:110)
	at org.apache.hive.service.CompositeService.init(CompositeService.java:59)
	at org.apache.hive.service.server.HiveServer2.init(HiveServer2.java:129)
	at com.klarna.hiverunner.HiveServerContainer.init(HiveServerContainer.java:85)
	at com.klarna.hiverunner.builder.HiveShellBase.start(HiveShellBase.java:150)
	at com.klarna.hiverunner.StandaloneHiveRunner.createHiveServerContainer(StandaloneHiveRunner.java:224)
	at com.klarna.hiverunner.StandaloneHiveRunner.evaluateStatement(StandaloneHiveRunner.java:176)
	at com.klarna.hiverunner.StandaloneHiveRunner.access$000(StandaloneHiveRunner.java:65)
	at com.klarna.hiverunner.StandaloneHiveRunner$1$1.evaluate(StandaloneHiveRunner.java:92)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at com.klarna.hiverunner.ThrowOnTimeout$1.run(ThrowOnTimeout.java:42)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient
	at org.apache.hadoop.hive.metastore.MetaStoreUtils.newInstance(MetaStoreUtils.java:1523)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.<init>(RetryingMetaStoreClient.java:86)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:132)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:104)
	at org.apache.hadoop.hive.ql.metadata.Hive.createMetaStoreClient(Hive.java:3005)
	at org.apache.hadoop.hive.ql.metadata.Hive.getMSC(Hive.java:3024)
	at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:503)
	at org.apache.hive.service.cli.CLIService.applyAuthorizationConfigPolicy(CLIService.java:125)
	at org.apache.hive.service.cli.CLIService.init(CLIService.java:110)
	at org.apache.hive.service.CompositeService.init(CompositeService.java:59)
	at org.apache.hive.service.server.HiveServer2.init(HiveServer2.java:129)
	at com.klarna.hiverunner.HiveServerContainer.init(HiveServerContainer.java:85)
	at com.klarna.hiverunner.builder.HiveShellBase.start(HiveShellBase.java:150)
	at com.klarna.hiverunner.StandaloneHiveRunner.createHiveServerContainer(StandaloneHiveRunner.java:224)
	at com.klarna.hiverunner.StandaloneHiveRunner.evaluateStatement(StandaloneHiveRunner.java:176)
	at com.klarna.hiverunner.StandaloneHiveRunner.access$000(StandaloneHiveRunner.java:65)
	at com.klarna.hiverunner.StandaloneHiveRunner$1$1.evaluate(StandaloneHiveRunner.java:92)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at com.klarna.hiverunner.ThrowOnTimeout$1.run(ThrowOnTimeout.java:42)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.apache.hadoop.hive.metastore.MetaStoreUtils.newInstance(MetaStoreUtils.java:1521)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.<init>(RetryingMetaStoreClient.java:86)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:132)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:104)
	at org.apache.hadoop.hive.ql.metadata.Hive.createMetaStoreClient(Hive.java:3005)
	at org.apache.hadoop.hive.ql.metadata.Hive.getMSC(Hive.java:3024)
	at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:503)
	at org.apache.hive.service.cli.CLIService.applyAuthorizationConfigPolicy(CLIService.java:125)
	at org.apache.hive.service.cli.CLIService.init(CLIService.java:110)
	at org.apache.hive.service.CompositeService.init(CompositeService.java:59)
	at org.apache.hive.service.server.HiveServer2.init(HiveServer2.java:129)
	at com.klarna.hiverunner.HiveServerContainer.init(HiveServerContainer.java:85)
	at com.klarna.hiverunner.builder.HiveShellBase.start(HiveShellBase.java:150)
	at com.klarna.hiverunner.StandaloneHiveRunner.createHiveServerContainer(StandaloneHiveRunner.java:224)
	at com.klarna.hiverunner.StandaloneHiveRunner.evaluateStatement(StandaloneHiveRunner.java:176)
	at com.klarna.hiverunner.StandaloneHiveRunner.access$000(StandaloneHiveRunner.java:65)
	at com.klarna.hiverunner.StandaloneHiveRunner$1$1.evaluate(StandaloneHiveRunner.java:92)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at com.klarna.hiverunner.ThrowOnTimeout$1.run(ThrowOnTimeout.java:42)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.jdo.JDODataStoreException: Required table missing : "VERSION" in Catalog "" Schema "". DataNucleus requires this table to perform its persistence operations. Either your MetaData is incorrect, or you need to enable "datanucleus.autoCreateTables"
	at org.datanucleus.api.jdo.NucleusJDOHelper.getJDOExceptionForNucleusException(NucleusJDOHelper.java:461)
	at org.datanucleus.api.jdo.JDOPersistenceManager.jdoMakePersistent(JDOPersistenceManager.java:734)
	at org.datanucleus.api.jdo.JDOPersistenceManager.makePersistent(JDOPersistenceManager.java:754)
	at org.apache.hadoop.hive.metastore.ObjectStore.setMetaStoreSchemaVersion(ObjectStore.java:6773)
	at org.apache.hadoop.hive.metastore.ObjectStore.checkSchema(ObjectStore.java:6670)
	at org.apache.hadoop.hive.metastore.ObjectStore.verifySchema(ObjectStore.java:6645)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.hive.metastore.RawStoreProxy.invoke(RawStoreProxy.java:114)
	at com.sun.proxy.$Proxy29.verifySchema(Unknown Source)
	at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.getMS(HiveMetaStore.java:572)
	at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.createDefaultDB(HiveMetaStore.java:624)
	at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.init(HiveMetaStore.java:461)
	at org.apache.hadoop.hive.metastore.RetryingHMSHandler.<init>(RetryingHMSHandler.java:66)
	at org.apache.hadoop.hive.metastore.RetryingHMSHandler.getProxy(RetryingHMSHandler.java:72)
	at org.apache.hadoop.hive.metastore.HiveMetaStore.newRetryingHMSHandler(HiveMetaStore.java:5762)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.<init>(HiveMetaStoreClient.java:199)
	at org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient.<init>(SessionHiveMetaStoreClient.java:74)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.apache.hadoop.hive.metastore.MetaStoreUtils.newInstance(MetaStoreUtils.java:1521)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.<init>(RetryingMetaStoreClient.java:86)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:132)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:104)
	at org.apache.hadoop.hive.ql.metadata.Hive.createMetaStoreClient(Hive.java:3005)
	at org.apache.hadoop.hive.ql.metadata.Hive.getMSC(Hive.java:3024)
	at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:503)
	at org.apache.hive.service.cli.CLIService.applyAuthorizationConfigPolicy(CLIService.java:125)
	at org.apache.hive.service.cli.CLIService.init(CLIService.java:110)
	at org.apache.hive.service.CompositeService.init(CompositeService.java:59)
	at org.apache.hive.service.server.HiveServer2.init(HiveServer2.java:129)
	at com.klarna.hiverunner.HiveServerContainer.init(HiveServerContainer.java:85)
	at com.klarna.hiverunner.builder.HiveShellBase.start(HiveShellBase.java:150)
	at com.klarna.hiverunner.StandaloneHiveRunner.createHiveServerContainer(StandaloneHiveRunner.java:224)
	at com.klarna.hiverunner.StandaloneHiveRunner.evaluateStatement(StandaloneHiveRunner.java:176)
	at com.klarna.hiverunner.StandaloneHiveRunner.access$000(StandaloneHiveRunner.java:65)
	at com.klarna.hiverunner.StandaloneHiveRunner$1$1.evaluate(StandaloneHiveRunner.java:92)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at com.klarna.hiverunner.ThrowOnTimeout$1.run(ThrowOnTimeout.java:42)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.datanucleus.store.rdbms.exceptions.MissingTableException: Required table missing : "VERSION" in Catalog "" Schema "". DataNucleus requires this table to perform its persistence operations. Either your MetaData is incorrect, or you need to enable "datanucleus.autoCreateTables"
	at org.datanucleus.store.rdbms.table.AbstractTable.exists(AbstractTable.java:485)
	at org.datanucleus.store.rdbms.RDBMSStoreManager$ClassAdder.performTablesValidation(RDBMSStoreManager.java:3380)
	at org.datanucleus.store.rdbms.RDBMSStoreManager$ClassAdder.addClassTablesAndValidate(RDBMSStoreManager.java:3190)
	at org.datanucleus.store.rdbms.RDBMSStoreManager$ClassAdder.run(RDBMSStoreManager.java:2841)
	at org.datanucleus.store.rdbms.AbstractSchemaTransaction.execute(AbstractSchemaTransaction.java:122)
	at org.datanucleus.store.rdbms.RDBMSStoreManager.addClasses(RDBMSStoreManager.java:1605)
	at org.datanucleus.store.AbstractStoreManager.addClass(AbstractStoreManager.java:954)
	at org.datanucleus.store.rdbms.RDBMSStoreManager.getDatastoreClass(RDBMSStoreManager.java:679)
	at org.datanucleus.store.rdbms.RDBMSStoreManager.getPropertiesForGenerator(RDBMSStoreManager.java:2045)
	at org.datanucleus.store.AbstractStoreManager.getStrategyValue(AbstractStoreManager.java:1365)
	at org.datanucleus.ExecutionContextImpl.newObjectId(ExecutionContextImpl.java:3827)
	at org.datanucleus.state.JDOStateManager.setIdentity(JDOStateManager.java:2571)
	at org.datanucleus.state.JDOStateManager.initialiseForPersistentNew(JDOStateManager.java:513)
	at org.datanucleus.state.ObjectProviderFactoryImpl.newForPersistentNew(ObjectProviderFactoryImpl.java:232)
	at org.datanucleus.ExecutionContextImpl.newObjectProviderForPersistentNew(ExecutionContextImpl.java:1414)
	at org.datanucleus.ExecutionContextImpl.persistObjectInternal(ExecutionContextImpl.java:2218)
	at org.datanucleus.ExecutionContextImpl.persistObjectWork(ExecutionContextImpl.java:2065)
	at org.datanucleus.ExecutionContextImpl.persistObject(ExecutionContextImpl.java:1913)
	at org.datanucleus.ExecutionContextThreadedImpl.persistObject(ExecutionContextThreadedImpl.java:217)
	at org.datanucleus.api.jdo.JDOPersistenceManager.jdoMakePersistent(JDOPersistenceManager.java:729)
	at org.datanucleus.api.jdo.JDOPersistenceManager.makePersistent(JDOPersistenceManager.java:754)
	at org.apache.hadoop.hive.metastore.ObjectStore.setMetaStoreSchemaVersion(ObjectStore.java:6773)
	at org.apache.hadoop.hive.metastore.ObjectStore.checkSchema(ObjectStore.java:6670)
	at org.apache.hadoop.hive.metastore.ObjectStore.verifySchema(ObjectStore.java:6645)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.hive.metastore.RawStoreProxy.invoke(RawStoreProxy.java:114)
	at com.sun.proxy.$Proxy29.verifySchema(Unknown Source)
	at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.getMS(HiveMetaStore.java:572)
	at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.createDefaultDB(HiveMetaStore.java:624)
	at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.init(HiveMetaStore.java:461)
	at org.apache.hadoop.hive.metastore.RetryingHMSHandler.<init>(RetryingHMSHandler.java:66)
	at org.apache.hadoop.hive.metastore.RetryingHMSHandler.getProxy(RetryingHMSHandler.java:72)
	at org.apache.hadoop.hive.metastore.HiveMetaStore.newRetryingHMSHandler(HiveMetaStore.java:5762)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.<init>(HiveMetaStoreClient.java:199)
	at org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient.<init>(SessionHiveMetaStoreClient.java:74)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.apache.hadoop.hive.metastore.MetaStoreUtils.newInstance(MetaStoreUtils.java:1521)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.<init>(RetryingMetaStoreClient.java:86)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:132)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:104)
	at org.apache.hadoop.hive.ql.metadata.Hive.createMetaStoreClient(Hive.java:3005)
	at org.apache.hadoop.hive.ql.metadata.Hive.getMSC(Hive.java:3024)
	at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:503)
	at org.apache.hive.service.cli.CLIService.applyAuthorizationConfigPolicy(CLIService.java:125)
	at org.apache.hive.service.cli.CLIService.init(CLIService.java:110)
	at org.apache.hive.service.CompositeService.init(CompositeService.java:59)
	at org.apache.hive.service.server.HiveServer2.init(HiveServer2.java:129)
	at com.klarna.hiverunner.HiveServerContainer.init(HiveServerContainer.java:85)
	at com.klarna.hiverunner.builder.HiveShellBase.start(HiveShellBase.java:150)
	at com.klarna.hiverunner.StandaloneHiveRunner.createHiveServerContainer(StandaloneHiveRunner.java:224)
	at com.klarna.hiverunner.StandaloneHiveRunner.evaluateStatement(StandaloneHiveRunner.java:176)
	at com.klarna.hiverunner.StandaloneHiveRunner.access$000(StandaloneHiveRunner.java:65)
	at com.klarna.hiverunner.StandaloneHiveRunner$1$1.evaluate(StandaloneHiveRunner.java:92)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at com.klarna.hiverunner.ThrowOnTimeout$1.run(ThrowOnTimeout.java:42)
	at java.lang.Thread.run(Thread.java:745)
```

How can I solve this problem? Thanks!

**Comment by PelleUllberg** [comment]
Not sure. Could it be that you have a hive-site.xml or similar on the
classpath. HiveRunner uses HiveConf. And when HiveConf is instantiated it
will search the classpath for files like hive-site.xml etc. If so, it will
attempt to use those configurations which in most cases are not compatible
with HiveRunner.

BTW: What version of Hive are you using?

/Pelle

**Comment by ChockChan** [comment]
In fact, I don't install hive locally. I want to use hiverunner for testing my hql scripts.

**Comment by PelleUllberg** [comment]
I don't really follow you. HiveRunner requires neither local nor remote
installation. It's all bundled in HiveRunner. The only thing you need is to
have HiveRunner on the classpath.

HiveRunner is intended as a local test fwk for writing regression tests for
your hql scripts/udf:s/serdes etc.

Is that the way you use it or do you attempt to use it for another purpose?

regards
/Pelle

**Comment by baloo-bear** [comment]
Hello,

I have the same error when trying to get HiveRunner to execute the example test:
java.lang.IllegalStateException: Failed to create HiveServer :Error applying authorization policy on hive 

This is a machine on which there is no hive installed, so there would be no hive-site.xml on the classpath.  I am running from eclipse with the built-in JUnit runner.

I have tried HiveRunner 3.2.0 and 3.0.0 with the same result.

I should note that I am running on Windows, and had to make changes in "StandaloneHiveRunner" and "StandaloneHiveServerContext" to remove the lines ".setWritable(true, false)" on the folders that get created, since those calls fail in Windows on TemporaryFolder.  But those are the only changes.

**Comment by massdosage** [comment]
Is this still an issue? If so we'd appreciate a PR with any changes you needed to make to get it working on Windows. I don't believe any of the developers run Windows so this will be difficult for us to reproduce.

**Comment by singhrajbir87** [comment]
Hello All, I am facing the same issue 
`"java.lang.IllegalStateException: Failed to create HiveServer :Error applying authorization policy on hive configuration: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient"`

Steps I performed
added the hiverunner dependency to my pom (4.1.0)

copied the hellohiverunner example unit test to my project and run it as junit.

I am running this on mac (eclipse)

below is the the log for the same error

```
java.lang.IllegalStateException: Failed to create HiveServer :Error applying authorization policy on hive configuration: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient
	at com.klarna.hiverunner.HiveServerContainer.init(HiveServerContainer.java:102)
	at com.klarna.hiverunner.builder.HiveShellBase.start(HiveShellBase.java:160)
	at com.klarna.hiverunner.StandaloneHiveRunner.createHiveServerContainer(StandaloneHiveRunner.java:217)
	at com.klarna.hiverunner.StandaloneHiveRunner.evaluateStatement(StandaloneHiveRunner.java:165)
	at com.klarna.hiverunner.HiveRunnerRule$HiveRunnerRuleStatement.evaluate(HiveRunnerRule.java:82)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at com.klarna.hiverunner.ThrowOnTimeout$1.run(ThrowOnTimeout.java:60)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Error applying authorization policy on hive configuration: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient
	at org.apache.hive.service.cli.CLIService.init(CLIService.java:117)
	at org.apache.hive.service.CompositeService.init(CompositeService.java:59)
	at org.apache.hive.service.server.HiveServer2.init(HiveServer2.java:142)
	at com.klarna.hiverunner.HiveServerContainer.init(HiveServerContainer.java:85)
	... 7 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient
	at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:512)
	at org.apache.hive.service.cli.CLIService.applyAuthorizationConfigPolicy(CLIService.java:129)
	at org.apache.hive.service.cli.CLIService.init(CLIService.java:114)
	... 10 more
Caused by: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient
	at org.apache.hadoop.hive.metastore.MetaStoreUtils.newInstance(MetaStoreUtils.java:1701)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.<init>(RetryingMetaStoreClient.java:83)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:133)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:104)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:97)
	at org.apache.hadoop.hive.ql.metadata.Hive.createMetaStoreClient(Hive.java:2879)
	at org.apache.hadoop.hive.ql.metadata.Hive.getMSC(Hive.java:2898)
	at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:493)
	... 12 more
Caused by: java.lang.NoSuchMethodException: org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient.<init>(org.apache.hadoop.hive.conf.HiveConf, org.apache.hadoop.hive.metastore.HiveMetaHookLoader, java.lang.Boolean)
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at org.apache.hadoop.hive.metastore.MetaStoreUtils.newInstance(MetaStoreUtils.java:1697)
	... 19 more


```

**Comment by massdosage** [comment]
What version of Hive are you using?

**Comment by singhrajbir87** [comment]
![image](https://user-images.githubusercontent.com/50380560/57339206-557c8380-70f6-11e9-9895-c65957162b0b.png)

These are all the hive dependencies I use in my project

**Comment by massdosage** [comment]
OK, I see the problem - you have a CDH version of Hive 1.1.0 and then also Apache Hive 2.3.3 on the classpath. Hive 1 and 2 are not compatible. You need to update your dependencies so that you have *only* Hive 2.3.3 libraries available. The best approach is probably to find out what is pulling in the CDH version of Hive and exclude it.

**Comment by singhrajbir87** [comment]
ok so I excluded all the dependencies and defined explicitly to 2.3.3 it bypassed that error and I got into libthrift error. 

Again I changed the version to libthrift-0.9.3.jar it worked

Now I am getting following  error where. I referred this post https://github.com/klarna/HiveRunner/issues/22 where they mention to exclude another dependency and define it explicitly (hsqldb) but still I am getting the same error. Please advise

Its failing to execute the query 
```
insert into my_schema.result
  select year, max(value) from source_db.test_table group by year 
```

```
java.lang.IllegalArgumentException: Failed to executeQuery Hive query insert into my_schema.result
  select year, max(value) from source_db.test_table group by year: Error while processing statement: FAILED: Execution Error, return code -101 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask. tried to access method com.google.common.base.Stopwatch.<init>()V from class org.apache.hadoop.mapreduce.lib.input.FileInputFormat
	at com.klarna.hiverunner.HiveServerContainer.executeStatement(HiveServerContainer.java:147)
	at com.klarna.hiverunner.builder.HiveShellBase.executeStatementsWithCommandShellEmulation(HiveShellBase.java:116)
	at com.klarna.hiverunner.builder.HiveShellBase.execute(HiveShellBase.java:150)
	at com.klarna.hiverunner.builder.HiveShellBase.execute(HiveShellBase.java:136)
	at com.cerner.revcycle.analytics.services.automatedBalancing.TestHive.testMaxValueByYear(TestHive.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.klarna.hiverunner.StandaloneHiveRunner.evaluateStatement(StandaloneHiveRunner.java:166)
	at com.klarna.hiverunner.HiveRunnerRule$HiveRunnerRuleStatement.evaluate(HiveRunnerRule.java:82)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at com.klarna.hiverunner.ThrowOnTimeout$1.run(ThrowOnTimeout.java:60)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hive.service.cli.HiveSQLException: Error while processing statement: FAILED: Execution Error, return code -101 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask. tried to access method com.google.common.base.Stopwatch.<init>()V from class org.apache.hadoop.mapreduce.lib.input.FileInputFormat
	at org.apache.hive.service.cli.operation.Operation.toSQLException(Operation.java:380)
	at org.apache.hive.service.cli.operation.SQLOperation.runQuery(SQLOperation.java:257)
	at org.apache.hive.service.cli.operation.SQLOperation.runInternal(SQLOperation.java:293)
	at org.apache.hive.service.cli.operation.Operation.run(Operation.java:320)
	at org.apache.hive.service.cli.session.HiveSessionImpl.executeStatementInternal(HiveSessionImpl.java:530)
	at org.apache.hive.service.cli.session.HiveSessionImpl.executeStatement(HiveSessionImpl.java:500)
	at org.apache.hive.service.cli.CLIService.executeStatement(CLIService.java:265)
	at com.klarna.hiverunner.HiveServerContainer.executeStatement(HiveServerContainer.java:120)
	... 18 more
Caused by: java.lang.IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class org.apache.hadoop.mapreduce.lib.input.FileInputFormat
	at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.listStatus(FileInputFormat.java:262)
	at org.apache.hadoop.hive.shims.Hadoop23Shims$1.listStatus(Hadoop23Shims.java:132)
	at org.apache.hadoop.mapreduce.lib.input.CombineFileInputFormat.getSplits(CombineFileInputFormat.java:217)
	at org.apache.hadoop.mapred.lib.CombineFileInputFormat.getSplits(CombineFileInputFormat.java:75)
	at org.apache.hadoop.hive.shims.HadoopShimsSecure$CombineFileInputFormatShim.getSplits(HadoopShimsSecure.java:321)
	at org.apache.hadoop.hive.ql.io.CombineHiveInputFormat.getCombineSplits(CombineHiveInputFormat.java:427)
	at org.apache.hadoop.hive.ql.io.CombineHiveInputFormat.getSplits(CombineHiveInputFormat.java:547)
	at org.apache.hadoop.mapreduce.JobSubmitter.writeOldSplits(JobSubmitter.java:624)
	at org.apache.hadoop.mapreduce.JobSubmitter.writeSplits(JobSubmitter.java:616)
	at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:492)
	at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1306)
	at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1303)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1671)
	at org.apache.hadoop.mapreduce.Job.submit(Job.java:1303)
	at org.apache.hadoop.mapred.JobClient$1.run(JobClient.java:564)
	at org.apache.hadoop.mapred.JobClient$1.run(JobClient.java:559)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1671)
	at org.apache.hadoop.mapred.JobClient.submitJobInternal(JobClient.java:559)
	at org.apache.hadoop.mapred.JobClient.submitJob(JobClient.java:550)
	at org.apache.hadoop.hive.ql.exec.mr.ExecDriver.execute(ExecDriver.java:411)
	at org.apache.hadoop.hive.ql.exec.mr.MapRedTask.execute(MapRedTask.java:151)
	at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:199)
	at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:100)
	at org.apache.hadoop.hive.ql.Driver.launchTask(Driver.java:2183)
	at org.apache.hadoop.hive.ql.Driver.execute(Driver.java:1839)
	at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1526)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1237)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1232)
	at org.apache.hive.service.cli.operation.SQLOperation.runQuery(SQLOperation.java:255)
	... 24 more

```

**Comment by massdosage** [comment]
We switched from using HSQLDB to Derby in HiveRunner 4.0.0 so the advice to remove that dependency probably isn't relevant here. I'm pretty sure the issue now is due to conflicting versions of Guava on the classpath, can you look into the dependencies that rely on Guava and what the different versions in use are? I'm guessing you need to make sure the Guava version in use is whatever version of Guava is required by Hive.

**Comment by singhrajbir87** [comment]
Thank you so much for the help @massdosage  I was able to resolve the issue by changing the Guava version.

I am calling the following script in the my test case as you see below I need to pass the input arguments for the script to run.

I am able to run the script If I hard coded the values inside the script. Is there a way I can call this script using hiverunner with the arguments ?  Any ideas please ?

```
DROP TABLE IF EXISTS ${tableName};

CREATE EXTERNAL TABLE ${tableName}
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.avro.AvroSerDe'
STORED AS
INPUTFORMAT 'org.apache.hadoop.hive.ql.io.avro.AvroContainerInputFormat'
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.avro.AvroContainerOutputFormat'
LOCATION '${inputDataPath}'
TBLPROPERTIES ('avro.schema.url'='${schemaLoc}');
```

**Comment by massdosage** [comment]
OK, would you mind taking the above question and sending that to the mailing list as it's no longer related to this issue. I'm going to close the issue now but what you're asking feels more like a general discussion asking for help and the mailing list is the best place to start that discussion. I'm pretty sure what you're asking for can be done, there are various ways of doing variable substitution in Hive scripts and HiveRunner supports all/most of them.

**Comment by massdosage** [comment]
Closing issue, root cause was mismatch between Hive versions and Guava - these need to be all set to the same versions and need to be compatible with the version of Hive under test.

**Comment by singhrajbir87** [comment]
@massdosage When I run just my hive test as Junit from eclipse it is working fine but when I build the whole project from command line it is giving me following error. 

Looks like another dependency issue. Please advise

```
java.lang.NoClassDefFoundError: org/apache/hadoop/mapred/MRVersion
	at org.apache.hadoop.hive.shims.Hadoop23Shims.isMR2(Hadoop23Shims.java:848)
	at org.apache.hadoop.hive.shims.Hadoop23Shims.getHadoopConfNames(Hadoop23Shims.java:919)
	at org.apache.hadoop.hive.conf.HiveConf$ConfVars.<clinit>(HiveConf.java:356)
	at org.apache.hadoop.hive.conf.HiveConf.<clinit>(HiveConf.java:105)
	at com.klarna.hiverunner.StandaloneHiveServerContext.<init>(StandaloneHiveServerContext.java:51)
	at com.klarna.hiverunner.StandaloneHiveRunner.createHiveServerContainer(StandaloneHiveRunner.java:190)
	at com.klarna.hiverunner.StandaloneHiveRunner.evaluateStatement(StandaloneHiveRunner.java:165)
	at com.klarna.hiverunner.HiveRunnerRule$HiveRunnerRuleStatement.evaluate(HiveRunnerRule.java:82)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at com.klarna.hiverunner.ThrowOnTimeout$1.run(ThrowOnTimeout.java:60)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.mapred.MRVersion
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.hadoop.hive.shims.Hadoop23Shims.isMR2(Hadoop23Shims.java:848)
	at org.apache.hadoop.hive.shims.Hadoop23Shims.getHadoopConfNames(Hadoop23Shims.java:919)
	at org.apache.hadoop.hive.conf.HiveConf$ConfVars.<clinit>(HiveConf.java:356)
	at org.apache.hadoop.hive.conf.HiveConf.<clinit>(HiveConf.java:105)
	at com.klarna.hiverunner.StandaloneHiveServerContext.<init>(StandaloneHiveServerContext.java:51)
	at com.klarna.hiverunner.StandaloneHiveRunner.createHiveServerContainer(StandaloneHiveRunner.java:190)
	at com.klarna.hiverunner.StandaloneHiveRunner.evaluateStatement(StandaloneHiveRunner.java:165)
	at com.klarna.hiverunner.HiveRunnerRule$HiveRunnerRuleStatement.evaluate(HiveRunnerRule.java:82)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at com.klarna.hiverunner.ThrowOnTimeout$1.run(ThrowOnTimeout.java:60)
	at java.lang.Thread.run(Thread.java:748)


Results :
```

**Comment by massdosage** [comment]
It looks like this is now a mismatch of Hadoop jar dependencies. What versions of the various Hadoop dependencies do you have resolved in Maven? They should all match and be the same as the versions the version of Hive you are using requires. I can only guess that Eclipse is setting up the Maven classpath in a different order to the command line which is why you're seeing different behaviour.

**Comment by singhrajbir87** [comment]
There was Hadoop jar dependencies mismatch and I went ahead and matched whatever version hiverunner is using ( I cloned hiverunner locally and saw the dependency tree)

I am still getting the above error as hadoop jar version looks same in both of the projects as you can see below. please advise

**Hadoop jar Dependencies in my project** 
![image](https://user-images.githubusercontent.com/50380560/57825215-86e2f800-7763-11e9-9726-5ef3bf4e5b0b.png)

![image](https://user-images.githubusercontent.com/50380560/57825198-79c60900-7763-11e9-8e0c-510cad91d09c.png)
![image](https://user-images.githubusercontent.com/50380560/57825235-97936e00-7763-11e9-9fe7-9ed945003947.png)
![image](https://user-images.githubusercontent.com/50380560/57825240-a11cd600-7763-11e9-8ed9-b1b9a9b37e17.png)

**Hadoop jar Dependencies in Hiverunner project**
![image](https://user-images.githubusercontent.com/50380560/57825277-bb56b400-7763-11e9-9cb2-5fa7f67547e6.png)
![image](https://user-images.githubusercontent.com/50380560/57825281-c3aeef00-7763-11e9-9800-880c44fd67f1.png)


From command line the error I am getting

**Comment by massdosage** [comment]
It looks like you still have a mix of Apache Hadoop version 2.7.0 jars (I see versions 2.7.0, 2.7.1 and 2.7.2 in your classpath) and CDH Hadoop 2.6.0-cdh-5.4.2 and 5.16.1 - ideally you want to get *all* the Hadoop dependencies onto the exact same version. I'd start off focusing on hadoop-core as I think that contains the class that appears to be missing.

**Comment by yc7799** [comment]
![image](https://user-images.githubusercontent.com/29529214/86450575-576ac280-bd4c-11ea-83e9-38dd78ce85c2.png)

**Comment by Philosophy7** [comment]
![Uploading 屏幕截图 2022-05-19 104739.png…]()

**Comment by massdosage** [comment]
The above looks like a mismatch between Hive, Hadoop and possibly HiveRunner versions. We'd need to see what all of those are to check why they're not compatible.
